### ISSUE TITLE
Can't connect to akatsuki!

### ISSUE THREAD

**Issue by kanaarima** [Lekuruu/osu.py#1]
Using server="akatsuki.gg" when initialising game client, I get this:

> Error on login: NOT_FOUND
> Ignoring...
> Login error: AUTHENTICATION_ERROR
> Authentication failed. Please check your username/password!
> Exiting...

User/password is correct, any idea?

**Comment by Lekuruu** [comment]
I got that issue as well when I was testing... I might need to look into this further.

**Comment by Lekuruu** [comment]
Alright. I finally got around to investigate this issue and it should now be fixed. (https://github.com/Lekuruu/osu.py/commit/a47b0eeeea0741b7f49c96b7772162093ad7e285)

Turns out the modern clients use `\n` instead of `\r\n` when logging in, which was a silly little mistake I made.
