### ISSUE TITLE
Events seems to not fire after a few reconnects

### ISSUE THREAD

**Issue by kanaarima** [Lekuruu/osu.py#2]
I'm not sure if this only applies to send message packets (so maybe its not joining channels), after a few disconnects (due to server crashing, no "bancho is restarting" messages), once it succeeds to connect it won't fire send messages event anymore.
Server is akatsuki.gg using a bot account (which is just a regular one basically), osu.py (version 1.1.2) is running under debian 11 and python 3.9.2 (from debian repo)

**Comment by Lekuruu** [comment]
Seems like I messed something up with re-initializing the client. The easiest thing would of course be to just exit, if the server connection failed.

Do you still have logs of that happening?

**Comment by Lekuruu** [comment]
Oh nvm. I maybe know what is going on here...

I am assuming you have a loop, that always restarts the game.

```python
game = Game(...)

while True:
    game.run()
```

I've made a `retry` argument for that purpose, that you could use like this:

```python
game = Game(...)
retry = False

while True:
    game.run(retry)
    retry = True
```

**Comment by Lekuruu** [comment]
Oh nvm. I maybe already know whats going on here...

As you may know, the `game.run()` function has a `retry` argument, which re-initializes the client:

```python
    def run(self, retry=False) -> None:
        if retry:
            # Reinitialize game
            self.__init__(
                self.username,
                self.password,
                self.server,
                self.stream,
                self.version_number,
                self.tourney,
            )
```

The only problem is that the `events` get re-initialized as well, meaning that they will just be cleared if you restart.
Thank you for reporting this issue!

**Comment by Lekuruu** [comment]
Let's hope this works :D
